baseURL = "https://davidwmcneill.github.io/"
languageCode = "en-us"
title = "DevOps Blog"

theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]


DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true
themesDir = "../.."
resourceDir = "../resources"

#[languages]
#  [languages.en]
#    title = "My blog"
#    weight = 1
#    contentDir = "content/en"
#  [languages.fr]
#    title = "Mon blogue"
#    weight = 2
#    contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
#  site_logo = "img/logo.svg"
#  description = "My DevOps Blog"
#  twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  github = "https://github.com/davidwmcneill"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-mid-gray"
  featured_image = "https://images.pexels.com/photos/87089/rocket-lift-off-liftoff-astronautics-87089.jpeg"
  recent_posts_number = 3
